### ISSUE TITLE
Error: spawn @newrelic\next ENOENT

### ISSUE THREAD

**Issue by Antonytm** [newrelic-experimental/newrelic-nextjs-integration#2]
I follow this instruction https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data and get the error message

For my case 
```
 "next:dev": "cross-env next dev"
```
becomes
```
 "next:dev": "cross-env NODE_OPTIONS='-r @newrelic/next' next dev"
```
but it doesn't work. And logs doesn't give me a clue, what is wrong.

```
The system cannot find the path specified.
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn @newrelic\next ENOENT
    at notFoundError (C:\Projects\alterra\Sitecore-Headless-Mammoth-2\mammoth-headless\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Projects\alterra\Sitecore-Headless-Mammoth-2\mammoth-headless\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Projects\alterra\Sitecore-Headless-Mammoth-2\mammoth-headless\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Projects\alterra\Sitecore-Headless-Mammoth-2\mammoth-headless\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn @newrelic\\next',
  path: '@newrelic\\next',
  spawnargs: [ 'next', 'dev' ]
}
ERROR: "next:dev" exited with 1.
```

What could be wrong?
Where should I look at?

**Comment by Antonytm** [comment]
It looks like some issue with `cross-env`.
